import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "../../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Luxury Chauffeur By Citi Soluton",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = { Name: "luxury chauffeur", Email: "info@citisolution.com" };

  return (
    <section>
      {/* <Navbar Name={data.Name} /> */}
      <main className="mt-[40px] mx-auto w-full py-6 lg:py-8 bg-white dark:bg-gray-900">
        {children}
      </main>
      {/* <Footer Name={data.Name} email={data.Email} /> */}
    </section>
  );
}
